#################################################################
###################### Hexo Configuration #######################
#################################################################

# Site
title: 流殃
description: 欢迎来到我的个人博客，这里是我的一些个人记录，希望能够给你带来一些帮助。
keywords: "流殃,heyi,sunheyi,hexo,next"
language: en
timezone: Asia/Shanghai
author:
# URL
url: https://sunheyi.com
permalink: posts/:abbrlink/
permalink_defaults:
abbrlink:
  alg: crc32  # 算法：crc16 或 crc32
  rep: hex    # 进制：dec 或 hex
# Directory
source_dir: source
public_dir: public
tag_dir: tags
archive_dir: archives
category_dir: categories
code_dir: downloads/code
i18n_dir: :lang
skip_render:
  - robots.txt
  - animate/*
  - highlight/*


# Writing
new_post_name: :title.md # File name of new posts
default_layout: post
titlecase: false # Transform title into titlecase
external_link:
  enable: true # Open external links in new tab
  field: site # Apply to the whole site
  exclude: ''
filename_case: 0
render_drafts: false
post_asset_folder: false
relative_link: false
future: true
syntax_highlighter: highlight.js
highlight:
  auto_detect: true
  line_number: true
  line_threshold: 0
  tab_replace: ""
  theme: 
  wrap: true
  hljs: true
prismjs:
  preprocess: true
  line_number: true
  line_threshold: 0
  tab_replace: ""
  theme: default

# Home page setting
index_generator:
  per_page: 6
  order_by: -updated,-date
# Category & Tag
default_category: uncategorized
category_map:
tag_map:

# Date / Time format
date_format: YYYY-MM-DD
time_format: HH:mm:ss

# Pagination
per_page: 7
pagination_dir: page

# Extensions
theme: next

archive_generator:
  per_page: 12
  yearly: true
  monthly: true
  daily: false

marked:
  # For preserve original quotes in code blocks.
  smartypants: false
  lazyload: true


auto_excerpt:
  enable: true
  length: 50 # 可以根据需要设置自动截断的字数

# 搜索
search:
  path: search.json
  field: all
# Waline
# For more information: https://waline.js.org, https://github.com/walinejs/waline
waline:
  enable: true #是否开启
  serverURL: comment.sunheyi.com # Waline #服务端地址，我们这里就是上面部署的 Vercel 地址
  locale:
  placeholder: 请文明评论呀 # 评论框的默认文字
  avatar: mm # 头像风格
  meta: [nick, mail, link] # 自定义评论框上面的三个输入框的内容
  pageSize: 10 # 评论数量多少时显示分页
  lang: zh-cn # 语言, 可选值: en, zh-cn
  # Warning: 不要同时启用 `waline.visitor` 以及 `leancloud_visitors`.
  visitor: true # 文章阅读统计
  comment_count: true # 如果为 false , 评论数量只会在当前评论页面显示, 主页则不显示
  requiredFields: [] # 设置用户评论时必填的信息，[nick,mail]: [nick] | [nick, mail]
  libUrl: # Set custom library cdn url
